/** @type {import('@cspell/cspell-types').CSpellUserSettings} */
export default {
  // Enable both language locale, e.g. to match `behaviour` word
  language: 'en,en-GB',
  // Do not lint files from gitignore
  useGitignore: true,
  ignorePaths: ['pnpm-lock.yaml', 'package.json', '*.svg'],
  ignoreRegExpList: [
    // <Fathom id="..."
    // <YoutubeEmbed id="..."
    /id=".+?"/g,
    /id: '.+?',/g,
    // Ignore GitHub usernames
    /Thanks \[@.+?]/g,
  ],
  cache: {
    // Cache result in node_modules/.cache instead of root of the project
    useCache: true,
    cacheLocation: 'node_modules/.cache',
  },
  // List of words to be always considered correct
  words: [
    // Names
    'svelteflow',
    'reactflow',
    'xyflow',
    'xyflowdev',
    'Sandpack',
    'hayleigh',
    'elkjs',
    'dagre',
    'Turborepo',
    'shadcn',
    'nextra',
    'Codesandbox',
    'moritz',
    'nhost',
    'opengraph',
    'lightningcss',
    'waku',
    'Fira',
    'twind',
    'quadtree',
    'publica',
    'FOSSY',
    'svelvet',
    'CISG',
    'VSBG',
    'solidjs',
    'Akulov',
    'Möller',
    'Straße',
    'Kohlfurter',
    'classcat',
    'spacebar',
    'Kreuzberg',
    'Teutoburger',
    'shiki',
    'Sumit',
    'npmtrends',
    'kaustubhxd',
    'Prezi',
    'MBSE',
    'Klack',
    'Gorzo',
    'Jesús',
    'Meixner',
    'webcola',
    'dagrejs',
    'graphlib',
    'notionhq',
    'Braks',
    'cryosphere',
    'Handelsregister',
    'Amtsgericht',
    'Finanzamt',
    'Körperschaften',
    'Telemedia',
    'rankdir',
    'rebrushing',
    'lcsfort',
    'Kaustubh',
    'Facu',
    'Montanaro',
    'Liveblocks',
    'Codecademy',
    'Reactjs',
    'timeago',
    'Filippo',
    'Valsorda',
    'Mailjet',
    'handholding',
    'crawlable',
    'svelty',
    'rels',
    'typosquat',
    'flowgraphs',
    'flextree',
    'destructures',
    'writables',
    'overwritable',

    // Rest
    'deeplink',
    'designy',
    'reactday',
    'nodeid',
    'signup',
    'fallblog',
    'nodrag',
    'onbeforedelete',
    'onconnectend',
    'onconnectstart',
    'onedgecreate',
    'ondelete',
    'multiselection',
    'threlte',
    'connectionline',
    'boxshadow',
    'subline',
    'connectingto',
    'connectingfrom',
    'connectionindicator',
    'textbg',
    'buttonedge',
    'selfconnecting',
    'nopan',
    'reconnectable',
    'dndnode',
    'datablocks',
    'supabase',
    'typeform',
    'webkid',
    'cooldown',
    'sindresorhus',
    'subflows',
    'resizer',
    'layouting',
    'zoomable',
    'pannable',
    'koro',
    'Burak',
    'nodemouseleave',
    'nodedragstart',
    'nodedrag',
    'nodedragstop',
    'ondisconnect',
    'passwordprotected',
    'nodemousemove',
    'nodeclick',
    'nodecontextmenu',
    'nodemouseenter',
    'hubql',
    'qand',
    'carto',
    'doubleloop',
    'entitree',
    'outgoer',
    'Outgoers',
    'foss',
    'hackernews',
    'nicetomeetyou',
    'woohoo',
    'teampic',
    'oninit',
    'edgeclick',
    'edgecontextmenu',
    'huuuuge',
    'Ahhh',
    'arrowclosed',
    'simplebezier',
    'pastable',
    'webaudio',
    'mindmap',
    'nocss',
    'mycustomnode',
    'Strg',
    'Lavigne',
    'panecontextmenu',
    'paneclick',
    'selectionclick',
    'selectioncontextmenu',
    'textinput',
    'layouted',
    'CAMELCOMPONENT',
    'customnode',
    'custominput',
    'nooo',
    'didn',
    'doesn',
    'aren',
    'couldn',
    'nosource',
    'notarget',
    'Swoopy',
    'nodedelete',
    'leemunroe',
    'tobiasmeixner',
    'OSPOs',
    'edgemouseenter',
    'edgemouseleave',
    'connectstart',
    'connectend',
    'threecolumns',
    'thincrustopencore',
    'someothernode',
    'portid',
    'Minimaps',
    'premade',
    'ughhh',
    'tipjar',

    // class names
    'floatingedges',
    'colorpicker',
    'nowheel',
    'darkflow',
    'providerflow',
    'dndflow',
    'zoomonscroll',
    'edgetypes',
    'lightflow',
    'updatenode',
    'ishidden',
    'validationflow',
    'panonscroll',
    'panonscrollmode',
    'captureelementclick',
    'capturezoompanescroll',
    'capturezoompaneclick',
    'zoomondbl',
    'nodesselection',
    'selectionpane',
    'zoompane',
    'randomnode',
    'changelogger',
    'nodeinspector',
    'nodeinfo',
    'edgebutton',
    'clickconnecting',
    'nokey',
    'nums',
    'firamono',
    'ntdapper',
    'checkboxwrapper',
    'bglabel',
    'tabcontent',
    // rename below
    'nodetoolbar',
  ],
};
