packages:
  - apps/*
  - sites/*
  - packages/*
  - scripts/*
  - configs/*

catalog:
  '@nhost/nhost-js': ^4.7.0
  '@tailwindcss/postcss': ^4.2.2
  '@types/node': ^22.19.17
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@xyflow/react': ^12.10.2
  '@xyflow/svelte': ^1.5.2
  '@xyflow/system': ^0.0.74
  eslint: ^9.39.4
  next: ^16.2.4
  next-sitemap: ^4.2.3
  nextra: ^4.6.1
  nextra-theme-docs: ^4.6.1
  prettier: ^3.8.3
  react: ^19.2.5
  react-dom: ^19.2.5
  tailwindcss: ^4.2.2
  typescript: ^5.9.3

patchedDependencies:
  nextra: patches/nextra.patch
