packages:
  - apps/*
  - sites/*
  - packages/*
  - scripts/*
  - configs/*

patchedDependencies:
  nextra: patches/nextra.patch

catalog:
  next: '^16.1.4'
  next-sitemap: '^4.2.3'
  nextra: '^4.6.1'
  nextra-theme-docs: '^4.6.1'
  '@nhost/nhost-js': '^4.2.2'
  react: '^19.2.3'
  react-dom: '^19.2.3'
  '@types/react': '^19.2.8'
  '@types/react-dom': '^19.2.3'
  '@types/node': '^22.19.7'
  eslint: '^9.39.2'
  prettier: '^3.8.0'
  typescript: '^5.9.3'
  '@xyflow/react': '^12.10.0'
  '@xyflow/svelte': '^1.5.0'
  '@xyflow/system': '^0.0.74'
  'tailwindcss': '^4.1.18'
  '@tailwindcss/postcss': '^4.1.18'
