table:
  name: user_subscriptions
  schema: public
configuration:
  column_config:
    subscription_plan_id:
      custom_name: subscription_plan_id
  custom_column_names:
    subscription_plan_id: subscription_plan_id
  custom_root_fields: {}
object_relationships:
  - name: user
    using:
      manual_configuration:
        column_mapping:
          user_id: id
        insertion_order: null
        remote_table:
          name: users
          schema: auth
select_permissions:
  - role: user
    permission:
      columns:
        - subscription_plan_id
      filter:
        user_id:
          _eq: x-hasura-user-id
      limit: 1
event_triggers:
  - name: subscription-change
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns:
          - subscription_plan_id
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{NHOST_FUNCTIONS_URL}}/events/subscription-change'
    headers:
      - name: nhost-webhook-secret
        value_from_env: NHOST_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
