import { getMetaConfigFromTitleLookup } from 'xy-shared';

const titleLookup = {
  'background-variant': 'BackgroundVariant',
  connection: 'Connection',
  'connection-line-component-props': 'ConnectionLineComponentProps',
  'connection-line-type': 'ConnectionLineType',
  'connection-state': 'ConnectionState',
  'coordinate-extent': 'CoordinateExtent',
  'default-edge-options': 'DefaultEdgeOptions',
  'delete-elements': 'DeleteElements',
  edge: 'Edge',
  'edge-change': 'EdgeChange',
  'edge-marker': 'EdgeMarker',
  'edge-props': 'EdgeProps',
  'fit-view-options': 'FitViewOptions',
  handle: 'Handle',
  'handle-connection': 'HandleConnection',
  'node-connection': 'NodeConnection',
  'internal-node': 'InternalNode',
  'marker-type': 'MarkerType',
  'mini-map-node-props': 'MiniMapNodeProps',
  node: 'Node',
  'node-change': 'NodeChange',
  'node-handle': 'NodeHandle',
  'node-origin': 'NodeOrigin',
  'node-props': 'NodeProps',
  'on-edges-change': 'OnEdgesChange',
  'on-nodes-change': 'OnNodesChange',
  'pan-on-scroll-mode': 'PanOnScrollMode',
  'panel-position': 'PanelPosition',
  position: 'Position',
  'pro-options': 'ProOptions',
  'react-flow-instance': 'ReactFlowInstance',
  'react-flow-json-object': 'ReactFlowJsonObject',
  'resize-params': 'ResizeParams',
  viewport: 'Viewport',
  'xy-position': 'XYPosition',
};

export default getMetaConfigFromTitleLookup(
  titleLookup,
  '/api-reference/types',
);
